export default {
  'CA':{
    "AB": "Alberta",
    "BC": "British Columbia",
    "MB": "Manitoba",
    "NB": "New Brunswick",
    "NL": "Newfoundland and Labrador",
    "NS": "Nova Scotia",
    "NT": "Northwest Territories",
    "NU": "Nunavut",
    "ON": "Ontario",
    "PE": "Prince Edward Island",
    "QC": "Quebec",
    "SK": "Saskatchewan",
    "YT": "Yukon"  
  },
  'ES': {
    "A Coruña": "A Coruña",
    "Alacant*": "Alacant",
    "Albacete": "Albacete",
    "Alicante": "Alicante",
    "Almería": "Almeria",
    "Andalucía": "Andalucía",
    "Araba*": "Araba",
    "Aragón": "Aragon",
    "Asturias": "Asturias",
    "Principado de Asturias": "Principado de Asturias",
    "Badajoz": "Badajoz",
    "Barcelona": "Barcelona",
    "Bizkaia": "Bizkaia",
    "Burgos": "Burgos",
    "Canarias": "Canarias",
    "Cantabria": "Cantabria",
    "Castelló*": "Castello",
    "Castilla y León": "Castilla y Leon",
    "Castilla-La Mancha": "Castilla-La Mancha",
    "Catalunya": "Catalunya",
    "Ceuta": "Ceuta",
    "Ciudad Real": "Ciudad Real",
    "Cuenca": "Cuenca",
    "Cáceres": "Caceres",
    "Cádiz": "Cadiz",
    "Córdoba": "Cordoba",
    "Euskal Herria": "Euskal Herria",
    "Extremadura": "Extremadura",
    "Galicia": "Galicia",
    "Gipuzkoa": "Gipuzkoa",
    "Girona": "Girona",
    "Granada": "Granada",
    "Guadalajara": "Guadalajara",
    "Huelva": "Huelva",
    "Huesca": "Huesca",
    "Illes Balears": "Illes Balears",
    "Jaén": "Jaen",
    "La Rioja": "La Rioja",
    "Las Palmas": "Las Palmas",
    "León": "Leon",
    "Lleida": "Lleida",
    "Lugo": "Lugo",
    "Madrid": "Madrid",
    "Comunidad de Madrid": "Comunidad de Madrid",
    "Melilla": "Melilla",
    "Murcia": "Murcia",
    "Región de Murcia": "Region de Murcia",
    "Málaga": "Malaga",
    "Nafarroa*": "Nafarroa",
    "Navarra": "Navarra",
    "Nafarroako Foru Komunitatea*": "Nafarroako Foru Komunitatea",
    "Ourense": "Ourense",
    "Palencia": "Palencia",
    "Pontevedra": "Pontevedra",
    "Salamanca": "Salamanca",
    "Santa Cruz de Tenerife": "Santa Cruz de Tenerife",
    "Segovia": "Segovia",
    "Sevilla": "Sevilla",
    "Soria": "Soria",
    "Tarragona": "Tarragona",
    "Teruel": "Teruel",
    "Toledo": "Toledo",
    "Valencia": "Valencia",
    "Comunidad Valenciana": "Comunidad Valenciana",
    "Valladolid": "Valladolid",
    "Zamora": "Zamora",
    "Zargoza": "Zargoza",
    "Ávila": "Avila"
  },
  'IE': {
    "County Carlow": "Carlow",
    "County Cavan": "Cavan",
    "County Clare": "Clare",
    "County Cork": "Cork",
    "County Donegal": "Donegal",
    "County Dublin": "Dublin",
    "County Galway": "Galway",
    "County Kerry": "Kerry",
    "County Kildare": "Kildare",
    "County Kilkenny": "Kilkenny",
    "County Laois": "Laois",
    "County Leitrim": "Leitrim",
    "County Limerick": "Limerick",
    "County Longford": "Longford",
    "County Louth": "Louth",
    "County Mayo": "Mayo",
    "County Meath": "Meath",
    "County Monaghan": "Monaghan",
    "County Offaly": "Offaly",
    "County Roscommon": "Roscommon",
    "County Sligo": "Sligo",
    "County Tipperary": "Tipperary",
    "County Waterford": "Waterford",
    "County Westmeath": "Westmeath",
    "County Wexford": "Wexford",
    "County Wicklow": "Wicklow"
  },
  'US': {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
  }  
}
